---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: focal
    image: ubuntu:20.04
  - name: jammy
    image: ubuntu:22.04
  - name: noble
    image: ubuntu:24.04
provisioner:
  name: ansible
verifier:
  name: testinfra
