---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: 'brianhartsock.zprezto'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'brianhartsock.zprezto'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies.
        run: |
          pip3 install -r requirements.txt
          ansible-galaxy install -r molecule/default/requirements.yml

      - name: Ansible lint
        run: ansible-lint

      - name: YAML lint
        run: yamllint .

      - name: Python lint
        run: flake8

  molecule:
    name: Molecule
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'brianhartsock.zprezto'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies.
        run: pip3 install -r requirements.txt

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
